version: '3'

services:
  backend:
    image: aaronlhma/demo4640backend
    env_file:
      - variables.env
  database:
    image: mysql
    env_file:
      - variables.env
  web:
    image: aaronlhma/demo4640frontend
    env_file:
      - variables.env
    ports:
      - 8080:80
    volumes:
     - ./frontend/templates:/etc/nginx/templates/
  startup:
    image: aaronlhma/demo4640startup
    env_file:
      - variables.env
    depends_on:
      - database
      - backend
    